version: '3.6'

services:
    mysql-database:
        ports:
            - '3306:3306'
        image: mysql:latest
        environment:
            MYSQL_DATABASE: strider
            MYSQL_ROOT_PASSWORD: strider
            MYSQL_USER: strider
        restart: always
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
    api-with-mysql:
        build:
            context: .
            dockerfile: ./api-with-mysql.dockerfile
        ports:
            - '3333:3333'
        depends_on:
            mysql-database:
                condition: service_healthy
        environment:
            - DATABASE_TYPE=mysql
            - DATABASE_HOST=mysql-database
            - DATABASE_NAME=strider
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=strider
            - PORT=3333
