version: '3.6'

services:
    mysql-database:
        ports:
            - '3306:3306'
        image: mysql:latest
        environment:
            MYSQL_DATABASE: posts
            MYSQL_ROOT_PASSWORD: posts
            MYSQL_USER: posts
        restart: always
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
    api-with-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - '3333:3333'
        depends_on:
            mysql-database:
                condition: service_healthy
        volumes:
            - ./:/usr/src/app
        entrypoint: ['/bin/bash']
        command:
            - -c
            - |
                yarn install
                yarn dev:api
        environment:
            - DATABASE_TYPE=mysql
            - DATABASE_HOST=mysql-database
            - DATABASE_NAME=posts
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=posts
            - PORT=3333
