version: '3.6'

services:
    mysql-database:
        ports:
            - '3306:3306'
        image: mysql:latest
        environment:
            MYSQL_DATABASE: '${DATABASE_NAME}'
            MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_USER: '${DATABASE_USERNAME}'
        restart: always
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
    api-with-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            mysql-database:
                condition: service_healthy
        environment:
            - DATABASE_TYPE=mysql
            - DATABASE_HOST=mysql-database
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - PORT=${PORT}
