version: '3.6'

services:
    mysql-database:
        ports:
            - '3306:3306'
        image: mysql:latest
        environment:
            MYSQL_DATABASE: strider
            MYSQL_ROOT_PASSWORD: strider
            MYSQL_USER: strider
        restart: always
    api-with-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '3333:3333'
        links:
            - mysql-database
        depends_on:
            - mysql-database
        environment:
            - DATABASE_TYPE=mysql
            - DATABASE_HOST=localhost
            - DATABASE_NAME=strider
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=strider
            - PORT=3333
    api-with-sqlite:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '3334:3334'
        environment:
            - DATABASE_TYPE=sqlite
            - PORT=3334
